#!/bin/bash
set -euo pipefail

# Applies schema and seed data to the local Postgres instance started by startup.sh.
# Uses db_connection.txt which is generated by startup.sh.

if [ ! -f "db_connection.txt" ]; then
  echo "db_connection.txt not found. Start the database first (startup.sh)."
  exit 1
fi

CONN_STR=$(cat db_connection.txt | awk '{print $2}')

echo "Applying schema..."
psql "$CONN_STR" -f schema.sql

echo "Seeding data..."
psql "$CONN_STR" -f seed.sql

echo "Done."
